<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="MediatR" />
	<PackageReference Include="Swashbuckle.AspNetCore" />
	<PackageReference Include="Swashbuckle.AspNetCore.Filters" />
	<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
	<PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Application\Application.csproj" />
		<ProjectReference Include="..\Utilities\Utilities.csproj" />
	</ItemGroup>	
	
</Project>